1. List 5 good codings practices that have been mentioned in this course.

- Always write meaningful comments!
- To use meaningful variable names
- To space out your code
- Keep it simple (don't reinvent the wheel)
- Use pyramid approach/top-down architecture(?)

2. Identify the keys and values and write the command to add the key "Orange" with value 1 to the dictionary.

In [ ]:
# Solution for problem two

# Identifying keys and values
mydict = {'Apple' : 3, 'Pear' : 5, 'Banana' : 2}

keys = ["Apple", "Pear", "Banana"]
values = [3, 5, 2]

print(keys, list(mydict.keys()))
print(values, list(mydict.values()))

# Add the key
mydict["Orange"] = 1
print(mydict)


3. Explain how dictionaries are different from lists, and how lists are different from tuples

Dictionaries hold key-value pairs, while lists hold values that have an internal numeric index that starts at zero. To add to a dictionary, simply assign a value to a key that doesn't exist. To add to a list, you use the `append()` function.

Lists are mutable, but tuples are not (they are immutable).

In [ ]:
# The tuple itself is immutable not necessarily the value

nums = [1, 2, 3]

nums_ = (nums, "hi")

nums[0] = 3

print(nums_)

4. Identify and explain 3 ways strings are similar to lists.

In [ ]:
# Solution for Q4

name = "Anthony"
ages = [19, 20, 21]

# Similarity number 1: You can loop through them directly
for char in name:
    print(char, end=" ")
print()
for age in ages:
    print(age, end=" ")
print()

# Similarity number 2: You can index them and slice them
print(name[0], ages[0], name[-1], ages[-1])
print(name[:-2], ages[:2])

# Similarity number 3: You can use len() on them
print(len(name), len(ages))

5. List all of the data types we have seen in this course and provide an example of each. Identify which ones are mutable and which are immutable

In [ ]:
# Four primitive data types: int, float, bool, string [all immutable]
age = 20 
gpa = 5.00
can_drink = False
name = "Anthony"

# "Collections": lists, tuples, dictionaries, set (all mutable except for dictionary)
myList = [1, 2, 3]
myTuple = (1, 2, 3)
myDictionary = {1: 2, 3: 4, 5: 6}
mySet = set()

6. In your own words, explain the difference between the top-down and bottom-up design methods. 
Name at least one advantage and one disadvantage for each.

**Top-down:** Top-down design method is when you take big tasks and break them down slowly into smaller, more manageable tasks until each task can be represented by a small snippet of code. One pro is that it is easier to plan how your code will be structured. One con is if you have really big tasks, it can be very painful to plan out and the snippets are hard to connect to one another if there are too many.

**Bottom-up:** Bottom-up design method is when you slowly build up to bigger tasks by connections to one another. The pro of this design method is that you start with small, testable pieces of code and then slowly connect everything together, allowing you to test as you go more easily. The con is that this is dependent on having enough small tasks and can be derailed by insufficient planning.

7. Describe the various components of a hierarchy. How can we use one in program design?

Usually you have nodes (parent or children) and leaves (nodes with no children). These nodes help highlight relationships from one task to another and one code snippet to another. Holistically, a hierarchy also helps create a structure and a plan for the entire program.

8. Does it matter if we use the same variable names inside a user defined function and the main 
program? Why (not)?

In [ ]:
# Solution to problem 8

# Answer is no due to local scope!

def add(a, b):
    a = 4
    b = 5
    print(a + b)

a = 3
b = 2
print(a + b, a, b)
add(a, b)
print(a, b)

9. Does it matter where in our code we write function definitions?

In [1]:
# Solution to 9 (answer is Yes because Python is a sequential language!)

y = x()

def x():
    print("Hi")

NameError: name 'x' is not defined

10. Can functions access main memory? How do we pass information into a function? Can functions 
return multiple values?

In [7]:
# Solution to Q10

# Part 1: Yes but be careful not to change it
def F(): 
    # a += 3 Error
    print(a)

a = 5
F()

# Part 2: Pass information using parameters
def G(a, b):
    print(a + b)

G(1, 2)

# Part 3: Yes (if you count a tuple to store multiple values)
def words():
    return "Anthony", "Ryan", "Sam", "Erica", "Casey"

print(words())

5
3
('Anthony', 'Ryan', 'Sam', 'Erica', 'Casey')


11.  What type of coding error do you hate the most and why?

I hate logic errors the most because they're the hardest to debug since they don't cause an actual error.

12.  When you are trying to fix your code, what are some alternatives to using a debugger?

Usually just `print` statements and reading code (maybe use paper).

13.  When would it be best to use the `myfile = open(...)` and `myfile.close()` commands for 
opening files as opposed to the `with open(...) as myfile:` command? 

You can use the former if you want to avoid reopening the file over and over again by opening at the very start of the program and closing at the very end of the program.

14.  When opening files, what is the difference between the designators r, w, r+, and a?

"r" is for read only, "w" is for write-mode, "a" is for append-mode, and "r+" is for read and writing mode. "a+" is for adppending and reading.

15.  What are the differences between `myfile.read()`, `myfile.readline()`, 
`myfile.readlines()`, and `list(myfile)`? 

`read()` gives you one big string with all the content in it. `readline()` gives you just the current line. `readlines()` gives you a list of all the lines and so does `list(myfile)`.


In [4]:
# Solution to 15

with open("E:\F23Exam2PracticeSolutions\Exam 2 Practice Problems\yo.txt", "r") as f:
    print(repr(f.read()))

with open("E:\F23Exam2PracticeSolutions\Exam 2 Practice Problems\yo.txt", "r") as f:
    print(repr(f.readline()))
          
with open("E:\F23Exam2PracticeSolutions\Exam 2 Practice Problems\yo.txt", "r") as f:
    print(repr(f.readlines()))
          
with open("E:\F23Exam2PracticeSolutions\Exam 2 Practice Problems\yo.txt", "r") as f:
    print(repr(list(f)))

'a\nb\nc\nd\ne'
'a\n'
['a\n', 'b\n', 'c\n', 'd\n', 'e']
['a\n', 'b\n', 'c\n', 'd\n', 'e']


16.  What command(s) are used to remove the leading and trailing whitespace in a string? To separate a string into a list of its components with a specified delimiter? Write an example using both

In [12]:
# Solution to 16

name = "\n\rAnthony  \n  \r"
print(repr(name.strip()))

letters = name.strip().split("n")
print(letters)

'Anthony'
['A', 'tho', 'y']


17.  Write the command to print the value of pi to 4 decimal places to the screen. Don’t forget to import pi from the math module!

In [1]:
from math import pi

print(f"{pi:.4f}")

3.1416


18.  Write the command to import the `coolfunc()` function from the neatomod module in the 
funpack package and rename it to `coolf`. Now write the command to import all functions from 
the neatomod module. What command can we use to obtain a list of all functions inside the 
module? 

In [ ]:
# Solution to Q18

from funpact import neatomod.coolfunc as coolf

from funpact.neatomod import *

print(dir(funpact.neatomod))

19. What are the differences between `np.arange()`, `np.array()`, and `np.linspace()`? How 
many rows and columns will the matrix `np.arange(15).reshape(5, 3)` have?

In [7]:
# Solution to Q19

from numpy import arange, array, linspace

print(arange(1, 11, 2))
print(array([1, 2, 3]))
print(linspace(1, 10, 19))

print(arange(15).reshape(5, 3).shape)
print(arange(15).reshape(5, 3))

[1 3 5 7 9]
[1 2 3]
[ 1.   1.5  2.   2.5  3.   3.5  4.   4.5  5.   5.5  6.   6.5  7.   7.5
  8.   8.5  9.   9.5 10. ]
(5, 3)
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


20.  What are the differences between plt.plot(), plt.bar(), plt.hist(), and 
plt.scatter()? How do you set the color of a line? The marker shapes? The axis labels? The 
title? The legend?

All four make a different type of graph (plot a line, plot a bar graph, plot a histogram, and plot a scatterplot). You can set the color by specifying a string that contains the appropriate color code. You can combine this with the linestyle in one string to change both. You can use `xlabel()` and `ylabel()` for the x and y axis labels. `title()` can set the title and `legend()` to help create the legend.

21.  Why is it important to include docstrings when writing functions? 

Docstrings help describe the function's use and what the parameters mean.