1. List 5 good codings practices that have been mentioned in this course.

- Comment your code (with meaningful comments)
- To use meaningful variable names
- Don't re-invent the wheel
- Keep it simple
- Plan out your code

2. Identify the keys and values and write the command to add the key "Orange" with value 1 to the dictionary.

In [1]:
mydict = {'Apple' : 3, 'Pear' : 5, 'Banana' : 2}

print(list(mydict.keys()), list(mydict.values()))
mydict["Orange"] = 1
print(mydict)

['Apple', 'Pear', 'Banana'] [3, 5, 2]
{'Apple': 3, 'Pear': 5, 'Banana': 2, 'Orange': 1}


3. Explain how dictionaries are different from lists, and how lists are different from tuples

In a list, the values are stored in a particular order and where they are in the list relative to one another determines their "index". But in a dictionary, all the values are associated with a unique key determined by the programmer. The list stores values in `[]` while the dictionary stores values in `{}`.

The tuple is immutable (cannot change values), while the list is mutable (can change values). Visually, the tuple stores items in `()` while the list stores in `[]`.

4. Identify and explain 3 ways strings are similar to lists.

In [3]:
# Similarity 1: You can use indexing and slicing on them with the same format
names = ["Anthony", "Dr. Ritchey", "Samantha"]
name = "Anthony"

print(names[0], name[0])
print(names[:-1], name[:-1])

# Similarity 2: You can loop through them with a for loop

for i in names:
    print(i)
for i in name:
    print(i)

# Similarity 3: You can use len()

print(len(names), len(name))

Anthony A
['Anthony', 'Dr. Ritchey'] Anthon
Anthony
Dr. Ritchey
Samantha
A
n
t
h
o
n
y
3 7


5. List all of the data types we have seen in this course and provide an example of each. Identify which ones are mutable and which are immutable

In [ ]:
# Primitive data types (all immutable)
age = 21   # int
gpa = 4.9  # float
is_guy = True  # boolean
name = "Anthony" # string

# Mutable collections
ages = [1, 2, 3]  # list
words = {"a": 1}  # dictionaries
unique_nums = set(ages) # sets

# Immutable collection
cant_change_this = (1, 2, 3)



6. In your own words, explain the difference between the top-down and bottom-up design methods. 
Name at least one advantage and one disadvantage for each.

Top-down design focuses on breaking bigger tasks into smaller, more manageable tasks that may be representable with a small chunk of code (could be a small function or just a handful of lines of code) while bottom-up design focuses on creating tasks from the get-go and building up/categorizing slowly. 

The advantage of top-down design is the ability to break down large chunks of work into more manageable sizes (which is preferrable in groups). The advantage of bottom-up design allows you to plan your immediate tasks from the get-go.

The disadvantage of top-down design is that the code may have low re-useability due to task specialization. The disadvantage of bottom-down design is that you may stray off track from the original idea/prompt.

7. Describe the various components of a hierarchy. How can we use one in program design?

A hierarchy contains various nodes (node = task). The top most node is your root (your primary objective) and your nodes without child nodes (nodes that branch that below them) are called leafs (your tasks that are directly translated into code). You can use them to plan out and structure your code (e.g. top-down and bottom-up design methods).

8. Does it matter if we use the same variable names inside a user defined function and the main 
program? Why (not)?

In [3]:
a = 2 

def hi():
    a = 3
    print("Inside function", a)

hi()
print("Outside function", a)

# The difference is due to global and local scope

Inside function 3
Outside function 2


9. Does it matter where in our code we write function definitions?

In [1]:
# Yes it does matter, you must define the function first

def y():
    return 2

x = y()

print(x)

2


10. Can functions access main memory? How do we pass information into a function? Can functions 
return multiple values?

Functions can read main memory but cannot directly change it. You can use parameters to pass information into a function. Functions cannot return multiple values, but it can return a tuple that contains multiple values itself.

11.  What type of coding error do you hate the most and why?

There are three types of errors: syntax, runtime, and logic. Logic errors are the ones I hate the most because they're the hardest to debug.

12.  When you are trying to fix your code, what are some alternatives to using a debugger?

One is to use your eyes. Two is to use a lot of `print()` statements.

13.  When would it be best to use the `myfile = open(...)` and `myfile.close()` commands for 
opening files as opposed to the `with open(...) as myfile:` command? 

Personally, I will use `open()` if I have to reuse the file over and over again at different spots. However, I generally prefer to use `with` because I can open multiple files at the same time and Python will guarentee the opened files will close correctly even if the program faces an unexpected error.

14.  When opening files, what is the difference between the designators r, w, r+, and a?

"r" is for read-only mode, "w" is for write-only mode, "r+" is for reading and writing mode, and "a" is for append mode.

15.  What are the differences between `myfile.read()`, `myfile.readline()`, 
`myfile.readlines()`, and `list(myfile)`? 

`read()` return a string with all the lines attached to each other in order. `readline()` will return the next line (moves the cursor down one) if there is a remaining line to read. `readlines()` and `list(myfile)` essentially do the same thing: returns a list of all the lines (each line is its own string).

16.  What command(s) are used to remove the leading and trailing whitespace in a string? To separate a string into a list of its components with a specified delimiter? Write an example using both

In [8]:
name = "  \n\t\r Anthony \n   \t   \r"

# Strip the string
print(repr(name.strip()))  # repr() outputs the raw version

# Split on a delimiter
print(name.split(" "))

'Anthony'
['', '', '\n\t\r', 'Anthony', '\n', '', '', '\t', '', '', '\r']


17.  Write the command to print the value of pi to 4 decimal places to the screen. Don’t forget to import pi from the math module!

In [1]:
from math import pi

print(f"{pi:.4f}")

3.1416


18.  Write the command to import the `coolfunc()` function from the neatomod module in the 
funpack package and rename it to `coolf`. Now write the command to import all functions from 
the neatomod module. What command can we use to obtain a list of all functions inside the 
module? 

In [2]:
from funpack.neatomod import coolfunc as coolf
from funpack.neatomod import *

# dir() is what you use to see all the functions inside the module
# below output is dir(math)

['__doc__',
 '__loader__',
 '__name__',
 '__package__',
 '__spec__',
 'acos',
 'acosh',
 'asin',
 'asinh',
 'atan',
 'atan2',
 'atanh',
 'cbrt',
 'ceil',
 'comb',
 'copysign',
 'cos',
 'cosh',
 'degrees',
 'dist',
 'e',
 'erf',
 'erfc',
 'exp',
 'exp2',
 'expm1',
 'fabs',
 'factorial',
 'floor',
 'fmod',
 'frexp',
 'fsum',
 'gamma',
 'gcd',
 'hypot',
 'inf',
 'isclose',
 'isfinite',
 'isinf',
 'isnan',
 'isqrt',
 'lcm',
 'ldexp',
 'lgamma',
 'log',
 'log10',
 'log1p',
 'log2',
 'modf',
 'nan',
 'nextafter',
 'perm',
 'pi',
 'pow',
 'prod',
 'radians',
 'remainder',
 'sin',
 'sinh',
 'sqrt',
 'tan',
 'tanh',
 'tau',
 'trunc',
 'ulp']

19. What are the differences between `np.arange()`, `np.array()`, and `np.linspace()`? How 
many rows and columns will the matrix `np.arange(15).reshape(5, 3)` have?

In [2]:
import numpy as np

print(np.arange(0, 10))
print(np.array([[1, 2, 3], [4, 5, 6]]))
print(np.linspace(0, 10, 30))

print(np.arange(15).reshape(5, 3))

[0 1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]]
[ 0.          0.34482759  0.68965517  1.03448276  1.37931034  1.72413793
  2.06896552  2.4137931   2.75862069  3.10344828  3.44827586  3.79310345
  4.13793103  4.48275862  4.82758621  5.17241379  5.51724138  5.86206897
  6.20689655  6.55172414  6.89655172  7.24137931  7.5862069   7.93103448
  8.27586207  8.62068966  8.96551724  9.31034483  9.65517241 10.        ]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


20.  What are the differences between plt.plot(), plt.bar(), plt.hist(), and 
plt.scatter()? How do you set the color of a line? The marker shapes? The axis labels? The 
title? The legend?

The differences between those four is the type of plot they make (standard line, bar graph, histrogram, and scatter plot). Inside the plotting function, declare the `color` to set the color. Also, you can declare the linestyle to change the marker shape. The axis labels can be changed with `set_xlabel()` and `set_ylabel()`. You can set the title with `title()` and set the legend with `legend()`.

21.  Why is it important to include docstrings when writing functions? 


This allows you to better document the function and lets users use the `help()`.

In [3]:
def hi():
    """ Says hi """
    print("Bye")

help(hi)

Help on function hi in module __main__:

hi()
    Says hi

